# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AiJyTAed7yBwmgCYtidxWNYXphHt54iB
"""

import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import matplotlib.pyplot as plt

# Upload the CSV
from google.colab import files
uploaded = files.upload()

# Read the CSV
df = pd.read_csv(list(uploaded.keys())[0])
df.head()

print(df.dtypes)

for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors='coerce')  # Convert valid numbers, set bad ones to NaN

print(df.dtypes)

df = df.dropna()

X = df.select_dtypes(include=['float64', 'int64'])

# Make sure it's not empty
print(X.shape)  # Should show something like (rows, columns)